/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}"
  ],
  darkMode: 'class',
  theme: {
    colors:{
      genericWhite: '#ffffff',
      genericBlack: '#000000',
      mainMenuCardsBackground: '#F5F8FF',
      mainMenuCardsHoverBackground: '#ebeef5',
      mainHeaderBackground: '#0A0A0B',
      tipsCalculatorMainBackground: '#C5E4E7',
      tipsCalcLabelTextColor: '#5e7a7d',
      tipsCalcInputColor: '#00494d',
      tipsCalcInputDivBG: '#f4fafa',
      tipsCalcInputDivOutline: '#26c0ab',
      tipsCalcBtnBG: '#00494d',
      tipsCalcBtnHover: '#a1e8e0',
      tipsCalcBtnTextHover: '#00494d',
      tipsCalcCustBtnBG: '#f4fafa',
      tipsCalcErrorText: '#e07152',
      tipsCalcRightBG: '#00494d',
      tipsCalcRightParag: '#7f9c9f',
      tipsCalcRightH1: '#26c0ab',
      tipsCalcResetBtn: '#5e7a7d',
      tipsCalcResetBtnText: '#00494d',
      tipsCalcResetBtnHover: '#a1e8e0',
      tipsCalcResetBtnActive: '#26c0ab',
      githubLightBg: '#f6f8ff',
      githubDarkBg: '#141d2f',
      githubSearchBarAndUserDetailsBgDark: '#1e2a47',
      githubTextLightGray: '#697C9A',
      githubSearchBtnBg: '#0079ff',
      githubErrorColor: '#f74545',
      githubUserDetailsContDarkBg: '#1e2b48',
      githubUserDetailsContLightBg: '#ffffff',
      githubUsernameText: '#0077ff',
      githubUserDetailsParagText: '#697c9b',
      githubAccountInfoBg: '#f5f7ff',
      githubAccountInfoBgDark: '#141d2f',
      githubSVGAndTextLightFill: '#4b699b',
      githubSVGAndTextUnavailableLight: '#8f95a8',
      loopStudioDescParag: '#8c8c8c',
      equalizerOfferBg: '#191826',
      equalizerPlanBg: '#fa7352',
      equalizerPlanText: '#fcf9f8',
      equalizerAppleBtnBg: '#191826',
      equalizerAppleBtnBgHover: '#65e2db',
      equalizerAndroidBtnBg: '#fcf9f8',
      equalizerAndroidBtnText: '#191826',
      equalizerAndroidBtnBgHover: '#ffba66',
      equalizerFooterIconsHover: '#fa7352',
      eComHeaderBorder: '#f7f8fd',
      eComNavTextColor: '#68707d',
      eComNavTextColorHover: '#1d2025',
      eComNavTextBorderHover: '#ff7d1a',
      eComOrangeColor: '#ff7d1a',
      eComLimitedH1Text: '#1d2025',
      eComDiscountBg: '#ffede0',
      eComOriginalPriceText: '#b6bcc8',
      eComQuantityBtnsBg: '#f7f8fd',
    },
    screens: {
      'phone': {'min': '320px', 'max': '767px'},
      'tablet': {'min':'768px', 'max': '1023px'},
      'laptop': {'min': '1023px', 'max': '1399px'},
      'desktop': {'min': '1440px'}
    },
    extend: {
      fontFamily: {
        'alata': ['"Alata"', 'sans-serif'],
        'josefin-sans': ['"Josefin Sans"', 'sans-serif'],
        'space-mono': ['"Space Mono"', 'monospace'],
        'ibm-plex': ['"IBM Plex Sans"', 'sans-serif'],
        'kumbh-sans': ['"Kumbh Sans"', 'sans-serif'],
      },
      backgroundImage: {
        'hero-desktop': "url('/src/assets/loop-studio/desktop/image-hero.jpg')",
        'hero-mobile': "url('/src/assets/loop-studio/mobile/image-hero.jpg')",
        'vr-goggles-desktop': "url('/src/assets/loop-studio/desktop/image-interactive.jpg')",
        'offer-desktop-bg': "url('/src/assets/equalizer/bg-pattern-2.svg')",
      },
      width: {
        '85%': '46.75rem',
        '70%': '42rem',
      },
      flex: {
        '2': '2 2 0%',
        '4': '4 4 0%',
      },
    },
  },
  plugins: [],
}
